### ISSUE TITLE
Update PYPI github secrets

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#248]
outdated:
```yaml
password: ${{ secrets.TELLIOT_FEED_EXAMPLES_TEST_PYPI_API_TOKEN }}
        password: ${{ secrets.telliot_feeds_TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish telliot-feeds to PyPI
      if: "!github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TELLIOT_FEED_EXAMPLES_PYPI_API_TOKEN }} 
        password: ${{ secrets.telliot_feeds_PYPI_API_TOKEN }} 
        ```
